export {
  API_ERROR_CODES,
  FORBIDDEN_READ_MESSAGE,
  type ApiErrorCode,
} from './error-codes';
export { ApiError, mapErrorBody, type ApiErrorBody } from './errors';
export {
  API_V1_PREFIX,
  BINDING_KINDS,
  P0_PATHS,
  POSTER_TEMPLATE_KEYS,
  ROLES,
  WATERMARK_POSITIONS,
  type Account,
  type Artwork,
  type ArtworkComment,
  type ArtworkCursorPage,
  type ArtworkCursorQuery,
  type AuthUser,
  type Binding,
  type BindingKind,
  type BindingQuery,
  type Brand,
  type CreateAccountRequest,
  type CreateArtworkFields,
  type CreateBindingRequest,
  type CreateCommentRequest,
  type CreateStudentRequest,
  type GeneratePosterRequest,
  type LoginRequest,
  type LoginResponse,
  type LogoutRequest,
  type LogoutResponse,
  type P0ErrorCode,
  type PosterDownload,
  type PosterPreview,
  type PosterTemplateKey,
  type RefreshRequest,
  type RefreshResponse,
  type Role,
  type Student,
  type TokenPair,
  type UpdateAccountRequest,
  type UpdateBrandRequest,
  type WatermarkPosition,
} from './dto';
export {
  EXAMPLE_ACCOUNT_DISABLED,
  EXAMPLE_ARTWORK,
  EXAMPLE_ARTWORK_PAGE,
  EXAMPLE_AUTH_USER,
  EXAMPLE_BINDING,
  EXAMPLE_BRAND,
  EXAMPLE_CONFLICT_BINDING,
  EXAMPLE_CONFLICT_STUDENT_HAS_ARTWORK,
  EXAMPLE_FORBIDDEN_READ,
  EXAMPLE_LOGIN_RESPONSE,
  EXAMPLE_LOGO_NOT_CONFIGURED,
  EXAMPLE_POSTER_DOWNLOAD,
  EXAMPLE_POSTER_DOWNLOAD_URL,
  EXAMPLE_POSTER_PREVIEW,
  EXAMPLE_POSTER_PREVIEW_URL,
  EXAMPLE_STUDENT,
} from './examples';
